[package]
name                  = "veryl-analyzer"
version               = "0.13.4"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools       = "0.14.0"
strnum_bitwidth = {workspace = true}
thiserror       = {workspace = true}
veryl-metadata  = {version = "0.13.4", path = "../metadata"}
veryl-parser    = {version = "0.13.4", path = "../parser"}
daggy           = "0.8.0"
bimap           = "0.6.3"

[target.'cfg(target_family = "wasm")'.dependencies]
miette          = {workspace = true, features = ["fancy-no-syscall"]}

[target.'cfg(not(target_family = "wasm"))'.dependencies]
miette          = {workspace = true, features = ["fancy"]}

[dev-dependencies]
toml = {workspace = true}
