[package]
name                  = "veryl-formatter"
version               = "0.13.4"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veryl-aligner  = {version = "0.13.4", path = "../aligner"}
veryl-metadata = {version = "0.13.4", path = "../metadata"}
veryl-parser   = {version = "0.13.4", path = "../parser"}
